apiVersion: memsql.com/v1alpha1
kind: MemsqlCluster
metadata:
  name: memsql-cluster
spec:
  license: BGMwMjNhOTQ5OGIyODQ0OGQ4ZDA2YzgwMTBlZDY1ZWQ0AAAAAAAAAAAEAAAAAAAAAAwwNAIYJODnInXo9x5UJUg//KYOEL7wASmFcGErAhgiOKidEd/6hANhqd2YnzB54GGeEKQyW9gAAA==
  adminHashedPassword: "*3D4DCF327388B190CCCBF672723AEC735B141813"
  nodeImage:
    repository: memsql/node 
    tag: centos-7.6.6-63e226ba05
    imagePullPolicy: IfNotPresent

  redundancyLevel: 1

  serviceSpec:
    objectMetaOverrides:
      labels:
        custom: label
      annotations:
        custom: annotations

  aggregatorSpec:
    count: 1
    height: 0.5
    storageGB: 256
    storageClass: spectrum-scale-sc

    objectMetaOverrides:
      annotations:
        optional: annotation
      labels:
        optional: label

  leafSpec:
    count: 2
    height: 0.5
    storageGB: 256
    storageClass: spectrum-scale-sc

    objectMetaOverrides:
      annotations:
        optional: annotation
      labels:
        optional: label
